### ISSUE TITLE
South Sudan- rTDY, Alex Bolo

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#11]
Alex Bolo, in-country SI advisor (interagency): requesting a rTDY at the end of August. Submitted ICPI Engagement Form on 6/11 (attached) 
[South Sudan rTDY request.pdf](https://github.com/ICPI/Engagements/files/2102752/South.Sudan.rTDY.request.pdf)

NEXT STEPS:
- Leads discussion to review/approve Eng request (Leads have been notified but we haven't yet reviewed details of the request)
- Confirm interagency support and buy-in for rTDY in country (Kashmira to send email)
- Set up call to discuss specifics of rTDY
- Send ICPI email once Leads approve

**Comment by kkale25** [comment]
Sent email to Tat'yana confirming interagency buy-in in country.

**Comment by kkale25** [comment]
- Need to add to Leads agenda to "approve"
- Kashmira to check in with Tat'yana and set up call with country team

**Comment by jb3436** [comment]
@kkale25 Let's follow up with this on Wed 7/18

**Comment by kkale25** [comment]
Tat'yana confirmed interagency in country agreement/buy-in/approval.

Next steps: 
- Kashmira to reach out to country team to finalize SOW (share draft Eth SOW); set up country call to move forward. 
- Send out large email.

**Comment by jb3436** [comment]
**Update 8/15**:  Received an update from Tat'Yana that Alex's dates have been postponed. No dates suggested yet. 

### To do in preparation
- [ ] finalize self directed tasks to utilize tools across clinical cascade and prevention programming
- [ ] Identify capstone project
- [ ] Idenfify follow on actions post rTDY

**Comment by kkale25** [comment]
Wrote another email checking in today re: new dates. Will move to "on hold" for the time being.
