### ISSUE TITLE
KP Analysis - HQ Request, Erin Eckstein

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#17]
Original request via ICPI Engagement Form submitted 6/25
[Erik Eckstein request.pdf](https://github.com/ICPI/Engagements/files/2136953/Erik.Eckstein.request.pdf)

**Comment by kkale25** [comment]
Leads approved request on 6/25. Notes from @jb3436 sent to @erinschelar @kimisatoPC, Erik, and Cedric on 6/25:

I would like to confirm that the ICPI leads reviewed your request and have approved it with the below feedback. We now transition the details over to the prevention cluster leads (Kimi Sato and Erin Schelar) to provide more detailed timelines, methods, and final deliverables based on their discussion with the analyst identified to complete the task.  
 
ICPI Leads Feedback:

·         Timeline – the analyst identified will not be able to completely finish the analysis by Thursday this week due to other requests. I believe next week is possible. This week the team can outline specific methods and provide a timeline for each of the steps. I defer to them to clarify the details. The below is an overview of the steps.
o   Project Overview, Timeline & Methods (by this Thursday)
o   Preliminary analysis (TBD)
o   Feedback from KPIF Team (TBD)
o   Final Product (TBD)
o   QC (1/2 day)
o   Clearance of final product (1-2 days)

·         Interpretation and use 
o   There are concerns around making sure that we don’t provide an analysis that could be misinterpreted
o   The prevention cluster will be sure to provide you with an analysis that both gets at the essence of your question as well as being as methodologically appropriate as possible. 
o   In many cases the data we collect in PEPFAR are unable to 100% answer all of the questions we have, but the ICPI team can be sure to present you with the options available givent eh data you have requested for analysis. 

·         Public distribution ready
o   The final product will likely need to be transferred into a software more in line with web and other distribution so the final public product is polished. The interactive exploratory analysis phase can be in whatever form you like (you requested excel), but the final graphics will likely be in Tableau or R and then converted to a PDF.

**Comment by kkale25** [comment]
@kimisatoPC @erinschelar Any updates on this request? Please include them here. Thanks!

**Comment by jb3436** [comment]
Duplicate ticket #15 Closing this one out.
