### ISSUE TITLE
Zambia Virtual Training (July 10th)

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/Engagements#18]
Objective: Support   to use Treatment analytic framework and Dashboards with possible   customization for GSM. Train at least on staff person in TSD Genie update

When: Scheduled for July 10 (TBC)

Lead POCs:  Zambia iSME's Minesh and Leigh (Shah, Minesh Pradyuman (CDC/CGH/DGHT) <yxi8@cdc.gov>; Tally, Leigh (CDC/CGH/DGHT) <yml4@cdc.gov>)

**Comment by jb3436** [comment]
This was completed. Will check in with @MicSherlock to see if there are any resources that could be linked here.
