### ISSUE TITLE
HRH PRE Analysis: Trends by Cadre & Grads and Spend -  Vamsi 

### ISSUE THREAD

**Issue by jb3436** [ICPI/Engagements#22]
Request Received: July 13, 2018
To be discussed at Leads Monday July 16, 2018
Requestor:  Vamsi Vassiredy

**Request**
As discussed earlier, I have a data request for the upcoming AFREhealth symposium where I am speaking and representing S/GAC. Please see below:
- Total number of health professions students that have graduated with PEPFAR support (HRH_PRE) since we started collecting data.
- HRH_PRE disaggregated by cadre for the years that have reliable/ consistent data.

Please let me know if it is possible to have this data by OOB Monday, July 23. Thank you.

**Next steps:**
- Determine who has time to cmplete request - LOE should be minimal... 30 mins - 1 hour. 
- Will determine if unpacking the PPR can quickly answer this question for more recent data
- May want to look at HRH dashboard for previous trend data

[SharePoint Project Location HSS Cluster HERE](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FShared%20Documents%2FClusters%2FHSS%2FProjects%2FHRH%20PRE%20Trend%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2-E166-4122-B8B4-7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)

FYI @kkale25

**Comment by jb3436** [comment]
Vamsi used the visuals from the analysis to create his slides for the AFREhealth symposium. The slides were cleared for use by OGAC.

Jasmien requested a copy of the slides to shared with the cluster and posted to the cluster folder.
FYI @kkale25 @wvp3 @Yabayabadoo

**Comment by jb3436** [comment]
![image](https://user-images.githubusercontent.com/13006198/44183317-80422a00-a0d8-11e8-9fa2-8824db5c1f51.png)

**Comment by jb3436** [comment]
Yaa and Kashmira QC'd values and they were triple for spend. Kashmira made updates to tables. Jasmine updated tableau visuals. 
Jasmine Emailed Vamsi 8/29
Subject: ICPI Request: HRH_PRE Analyses

**Comment by wvp3** [comment]
Request from S/GAC to update the HRH_PRE global numbers (tables and charts) previously assembled by @kkale25 In FY2017.

Product to be considered for inclusion in S/GAC World Health Day reporting.

The updated tables and charts were requested and completed on 3/25/2020. A QC review is recommended prior to confirming external dissemination.

[https://www.pepfar.net/sites/icpi/Shared%20Documents/Clusters/HSS/Projects/HRH%20PRE%20Trend%20Analysis/HRH_PRE%20Analyses_3-25-2020.xlsx](url)

**Comment by wvp3** [comment]
QC complete and visuals (bar charts) from FY18 and FY19 numbers matched raw MSD pivot tables.  However there was a minor discrepancy between MSD and DATIM for FY2019 only (Kenya reported 99 Social service workers trained and 99 midwives trained in DATIM... but not in MSD.  Unclear which source is correct.  Figures are based on MSD).
