### ISSUE TITLE
Follow Up rTDY Activities: Trust - Zimbabwe and Daniel - Ethiopia

### ISSUE THREAD

**Issue by jb3436** [ICPI/Engagements#28]
Follow Up activities for Summer rTDYs
---
### Zimbabwe - Trust https://github.com/ICPI/Engagements/issues/8

**July 2018** 

- Trust provided a debrief to the interagency team in country and it was well received. 
- The inter agency in country team has requested follow up ICPI support based on Trust's debrief to them. 

### Zimbabwe Next steps

- [x] Follow up on activities (via email)
- [x] Request debrief slides from Trust and post them to [sharepoint here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FZimbabwe%2FTrust%20rTDY&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)
- [x] Schedule a call to check in on activities

![image](https://user-images.githubusercontent.com/13006198/44157968-a7214180-a081-11e8-92a7-ce8a2239777d.png)

### Ethiopia - Daniel https://github.com/ICPI/Engagements/issues/6

**August 10, 2018** 
Daniel presented his outbrief to ICPI and the file is saved on [SharePoint here](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FEthiopia%2FPEPFAR%20Coordinator%20SI%20rTDY%20Fellowship&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

### Ethiopia Next Steps

- [x] Send follow up engagement email to his country team
- [ ] Send follow up survey about his time at ICPI
- [x] Get debrief slides from his check in with the country team
- [ ] Get final products from capstone and save on sharepoint

**Comment by jaliasd** [comment]
Just a quick comment: In the follow up call with Trust, could we request if he has plans to do any interagency trainings as part of the afters of his rTDY? I had a debrief with the USAID/ZIM SI team and they expressed a desire for training/orientation to some ICPI tools and Pano, which I think Trust could probably do. -thanks

**Comment by kkale25** [comment]
Hi @hessionra, please see below for the email for Zim. Others - please make edits as you see fit.

Subject: ICPI Reverse TDY from Zimbabwe: Completed

Hello Zimbabwe Team (In Country & HQ),

Please forward to relevant colleagues who are not on this email.

ICPI is reaching out to ensure that our colleagues are aware of a complete engagement request.

This email intends to open the lines of communication. Please see below for additional details.

Title: ICPI Reverse TDY from Zimbabwe
Visit Dates: May 21 - June 1, 2018

Context:
In April, the Zim CDC team sent in a request for a two-week Reverse TDY to ICPI for Trust Chiguvare, CDC M&E Specialist. The main goal of the RTDY was for Trust to gain a deeper understanding of the ICPI core data management, analytic and visualization tools. Including:
• Using DATIM Genie extracts to update ICPI tools like the PPR and TSD
• Improving the in-country Partner Monitoring Dashboard through visualizations and data integration
• Refreshing on PALS training (with focus on DRT) so Trust can bring back materials to interagency team and continue knowledge sharing and building

Timeline of Activities:
• Initial engagement approved by ICPI Leads at the end of April
• Preliminary call with CDC Zim team on May 13
• Trust arrived at ICPI on May 21 and completed the RTDY on June 1
• Follow-up call with the interdisciplinary Zim team to discuss ICPI support and next steps on July 12

Next Steps:
• ICPI: Set up another follow-up call to discuss additional next steps and ICPI support requests
• Field Team: Share in-country rTDY debrief and discussions
• HQ: Chair, CL, SI Advisor, and ECT Management provide comments (if any).

Kindly respond with your comments, questions, or concerns.

Engagement POCs:
 ICPI: Kashmira Kale, Jamie Houston, Josh Davis, Jasmine Buttolph 
 In Country: Laurie Fuller, Shirish Balachandra, Trust Chiguvare

Please feel free to contact ICPI@state.gov if you have any questions, concerns, or if you would like any additional information.

Thank you,

ICPI

**Comment by kkale25** [comment]
@hessionra  In the email, can you edit the word "SharePoint" (last bullet under the Context section) and edit the word to include the hyperlink included? Thanks!

**Comment by jb3436** [comment]
I made minor updates above. Looks good to me. 

FYI @kkale25 @hessionra

**Comment by kkale25** [comment]
Sent check in emails to both Ethiopia and Zim teams. Requested products, debrief slides, etc. as needed. Will update here with the responses.

**Comment by kkale25** [comment]
Ethiopia team responded saying they were on track to finish the capstone in the next few weeks.

Zim team responded saying they will get back to us about a suitable time to meet to follow-up on next steps.

**Comment by jb3436** [comment]
Discussed Follow up engagement with Zim team. Let's create a new issue for Zim now that the request has solidified and there is a timeline. 

@kkale25

**Comment by jb3436** [comment]
Ethiopia
--
Daniel confirmed that he has no final products and has not been able to meet with the SI TWG in country to present on his ICPI TDY. We will follow up again next month and close out the ticket.

**Comment by kkale25** [comment]
Seems it's OK to close this engagement. I will check in with Trust one more time to see if they need any more support.
