### ISSUE TITLE
HRH Analysis - Cote D'Ivoire Post TDY Analysis -Vamsi

### ISSUE THREAD

**Issue by HoustonJamie** [ICPI/Engagements#33]
CDI HRH Analysis
--
Request Received: August 31, 2018
Discussed at Leads Monday Sept 4, 2018

**Request**
 There was a TDY to CDI last week of August to review HRH allocation and alignment to program targets and performance. During TDY Vamsi requested the country do a HRH rapid site assessment across a selection of 80 sites to understand 1) Which kinds of cadres preformed key tasks (testing, initiation, clinical follow up, adherence counseling, etc) at these sites 2) Determine a patient to worker ratio for the top performing sites considering the characteristics above.  

**Analysis request:**
Need to merge HRH site assessment data with MER (TX_NET_NEW) for large and small volume sites to determine the patient to worker ratio at top and bottom performing sites in collaboration with HQ HRH SMEs and interagency representatives from country team.   Learning lessons from similar analysis in South Africa and Malawi. 

**Due Date:**
 TBD, waiting on dataset to be shared (currently there is some issue with merging the data collection forms from excel into one file, file was corrupted) 

**Final Due date:**
 TBD 

**Next steps:**
- identify POCs from Country team (especially SI) 
- receive dataset from country team 
- likely need one round of dataset review with country team to resolve issues/roles/responsibilities then discuss with HRH SMEs.
- complete analysis and do QC
- include source, caveats, branding, and acknowledgements, and findings
- send to Vamsi for review
- request follow up on how analysis was used
- send to leads as FYI
- schedule at brownbag? (likely with the other HRH analysis) 

Resources: 
--
[CDI HRH Analysis Folder on SP](https://www.pepfar.net/OGAC-HQ/icpi/SharedDocuments/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHSS%2FProjects%2FCDI%20HRH%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)

**Comment by HoustonJamie** [comment]
Update: 9.19 
-Received dataset from HRH HQ SMEs (Cate, Adrienne, Vamsi) (posted to sharepoint here 
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHSS%2FProjects%2FCDI%20HRH%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2EDocument&VisibilityContext=WSSTabPersistence
-Identified primary analyst, Travis Lim @wvp3  
-Proposed tentative deadline for completion of primary analysis, 9/28

**Comment by kkale25** [comment]
Update 9/25:

Travis - Primary analyst
Yaa and Kashmira- Support

- Kashmira to support getting the MER data for CDI (Tx curr, tx new, net new)
- @wvp3 working on reformatting CDI dataset from country to be able to merge with MER dataset
- @wvp3/ @Yabayabadoo to work through analysis as appropriate
- Kashmira to help QC

**Comment by jb3436** [comment]
@wvp3 @kkale25 do we have an updated completion date?

**Comment by kkale25** [comment]
@wvp3 - Can you link the final product for this request and close the issue? 

Thanks!

**Comment by kkale25** [comment]
@wvp3 Flagging for travis to update with final product and close issue here.

**Comment by kkale25** [comment]
Final Product can be found here: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FClusters%2FHSS%2FProjects%2FCDI%20HRH%20Analysis&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D
