### ISSUE TITLE
GIS Request ECT4

### ISSUE THREAD

**Issue by jb3436** [ICPI/Engagements#36]
ECT4 GIS Request for STAR OUS
--
**Dates**:
- Received 10/2
- Due: 10/8

**Email subject**: Mapping request from ECT IV

**Approval**: Part of GIS team purview - communication will be sent to leads and other stakeholders

**Next Steps:**
- [x] Zhanar to attempt to complete request by 10/5 and QC 10/8
- [x] Request sent to Nate and Ed to potentially support QC
- [x] Send final QCd maps to Travis who will distribute to ECT4
- [x] Save maps on SharePoint and include link **[HERE](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FECT4&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D)**
- [x] Provide update on inbrief
- [x] Share maps with ICPI

Summary of Request
--
ECT IV has a basic request – we would like some simple maps of all “Asia” STAR countries with their PSNU boundaries and shaded with their COP prioritization level to demonstrate where PEPFAR is focusing resources, ideally as a jpg or png graphic output.  

The second step is to add Key pops prevalence data from IBBS studies and pop size estimates for KP.  These may be done as simple callouts or arrows even in powerpoint (doesn’t have to be sophisticated) and this can be done by myself or ECT IV since we have a database.  A crude example from the Burma POART was pulled by Maria Au from USAID:

The analytic question or goal for this is to determine (or demonstrate) that PEPFAR is indeed focusing investments toward geographic areas with high HIV prevalence and/or high numbers of key affected populations.  A possible supplemental map would be to show DSD+TA cumulative FY2018q3 results for HTS_TST or TX_NEW (Key population results only, not total numerator) as the choropleth instead of prioritization.  The timeline for this, working backwards:
- Present this at the Asia regionalization meeting Nov 4-9; a week before that DPs need to review; at least a week before that country teams need to review; at least a week before that ECT IV wants to review; 
- So that leaves us with a due date of COB October 12 to create the combined maps plus population size estimates and prevalence, though we are looking to get the standalone maps (without IBBS prevalence or pop size estimates) early next week so we can add in that data just in powerpoint OR we can share the dataset with that information for the GIS group to add in using a more sophisticated method like ArcGIS labels.

A list of the “Asia” countries we are working on that are planned to form the new Asia regional program is attached.  

Please let us know what would be possible or if this already exists somewhere.  I see the COP18 maps that Dustyn posted only have LTS in them.

Many thanks!

ECT IV

**Comment by kzhanar** [comment]
Provided maps for Vietnam and Ukraine Priority Levels 2018. Reused existing COP18 maps. 

![ukraine_priority_levels](https://user-images.githubusercontent.com/12820153/48165460-ac261380-e2b3-11e8-9bbd-8a650aeeaf17.jpg)
![vietnam_priority_levels](https://user-images.githubusercontent.com/12820153/48165461-ac261380-e2b3-11e8-811f-ed6e6eb46ef6.jpg)

**Comment by kzhanar** [comment]
ECT IV Map Outputs: 

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FECT4&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence

**Comment by kzhanar** [comment]
ECT IV Map Outputs: 

https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FECT4&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence
