### ISSUE TITLE
Index Testing COOP New Visual Request

### ISSUE THREAD

**Issue by bshook** [ICPI/Engagements#39]
A request from the COOP to have seperate Index Testing visuals that were easy to navigate to in response to POART priorities. 

9/24/18: Inquiry submitted to Jasmine re: testing visuals
10/10/18: Meeting with Mike Grillo and Shaylee to clarify request
10/15/18: Meeting with Shazad, Brittney, Shabeen, and Mike to nail down request: Mike was wanting Index Testing visuals to be incorporated into Pano and linked to COOP sharepoint page. Due to timeline agreed that it would be best to incorporate visuals into current excel tool. The visuals the COOP team were hoping to add had been mocked up in other tools and those were circulated to the group. 
10/16/18: Shazad, Shabeen, and Brittney met in small group to discuss the exact visuals and analytic questions to include. Shazad agreed the work could be completed prior to Q4 since they visuals had already been mocked up.
10/22/18: Brittney discussed engagement request with Leads. There were no issues

Reference Visuals: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Clusters/HIV-TB%20Diagnosis/Working%20Folder/HTS%20specific%20workbook%20FY18Q3_9.21.2018.twbx

**Comment by bshook** [comment]
10/30/18 Shazad submitted a draft of the updated CHIPs tool w/ Index Visuals to Shabeen, Brittney, and Shaylee for review

**Comment by kkale25** [comment]
@shazadahmed10 and @randyyee created HTS_INDEX visuals in CHIPS and have a select few visuals in the Initial FY19 Q2 version posted: https://www.pepfar.net/_windows/default.aspx?ReturnUrl=%2fect-m%2fect4%2f_layouts%2f15%2fAuthenticate.aspx%3fSource%3d%252Fect%252Dm%252Fect4%252FShared%2520Documents%252Ftarget%2520trend%252DECT4%252Ddatapacks%252DFeb21%2520group%255Fwbudgets%255F2%252D27%252D2019%252Exlsx&Source=%2fect-m%2fect4%2fShared+Documents%2ftarget+trend-ECT4-datapacks-Feb21+group_wbudgets_2-27-2019.xlsx
