### ISSUE TITLE
ECT I Request: Assessing Current status of OU vs. Figure 2.3.1 in COP19 Guidance

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/Engagements#43]
Request from ECT I and OGAC to categorize expenditure reporting according to the following 3 direct and non-direct service areas and display where countries are in comparison to the figure.

1.	Display percent of NSD/SD per program out of total expenditure
2.	Display percent of NSD/SD per program out of total expenditure (excluding PM program area)
3.	Group OUs by ARV Coverage (COP 17): 
a.	All PLHIV 
b.	Diagnosed PLHIV

See figure on page 36 of [Draft COP19 Guidance.](https://www.pepfar.gov/reports/guidance/287906.htm)

ECT I liaison request to ICPI leads for the following support:

- [ ] 	Can I have an analyst pull the ARV coverage rates from COP 17 datapacks for all OUs (All PLHIV & Diagnosed PLHIV)? I need this by OOB Tuesday. Analysis deadline is COB Wednesday.
- [ ] 	Can I have an analyst to QC the final version before we share with Kate and Italia?

**Comment by jaliasd** [comment]
@Yabayabadoo Do you want COP17 or COP18?

**Comment by jaliasd** [comment]
I have extracted all the ART and PLHIV from the COP18 datapacks (that I had). I need a bit of help to 1) make sure I have all of the latest datapacks 2) double check my figures. For #2 I spot checked a few and it seems my code worked (yay!) but probably needs more rigorous QC.

Where can I post this?

**Comment by Yabayabadoo** [comment]
Hi Josh! Thank you for doing this! Can we please post in the HSS cluster folder?
