### ISSUE TITLE
ECT2 Viral load tool

### ISSUE THREAD

**Issue by anu87** [ICPI/Engagements#44]
ECT2 group requested site-level analyses for ECT2 countries. The ask was to categorize sites into four categories based on their proxy-VL coverage (VLC) and VL suppression (VLS) and have the ability to examine the VLC & VLS by age/sex, for pregnant & breastfeeding women for high and low performing sites.

Presented the first version of the tools to ECT2 team during their meeting in Atlanta (8-10 Jan '19) and developed a second version based off of feedback. Final tools are available here:

[https://www.pepfar.net/ect-m/ect2/Shared%20Documents/Forms/AllItems.aspx?RootFolder=/ect-m/ect2/Shared%20Documents/Data%20Analysis/VL%20Site%20Level%20Analysis%20FY18Q4&FolderCTID=0x012000BB9BB6245625D94C9D036BB947B8D25F&View={8C7F09FA-5151-475C-93E7-470F22881AD2}](url)

**Comment by jb3436** [comment]
@anu87 is this also being updated for ECT 3?

**Comment by anu87** [comment]
ECT3 tools are being QC'd, will be released tomorrow

**Comment by jb3436** [comment]
Incorporated into the new 3rd 90 dossier
