### ISSUE TITLE
ECT 3 Priority Areas Analytic Support (HTS, Peds, Ret, VL)

### ISSUE THREAD

**Issue by jb3436** [ICPI/Engagements#45]
Priority Areas for ECT 3 and POCs
--

**- Viral Load:**  Peter Funjungo and Sarita Shah - (ICPI - Yaa and Anu)
**- Pediatrics:**  Molly Rivadeneira, Amelia Peltz, and Helen Dale (ICPI Katie and Jasmine)
**- Retention:**  Bill Coggin, John Aberle-Grasse, Elliot Raizes and Jacquie Firth (ICPI Michelle and Katie)
**- Case Finding:**  Irene Benech and Margo Salon (ICPI - Shazad and Anu)

**Comment by shazadahmed10** [comment]
ECT3 PITC tool created and delivered on 1/29. Same tool that was created fro ECT2.

Link: https://bit.ly/2WuW5O7
