### ISSUE TITLE
ECT 2 PITC Analysis

### ISSUE THREAD

**Issue by jb3436** [ICPI/Engagements#46]

**Comment by jb3436** [comment]
SharePoint Folder Here
--
https://www.pepfar.net/ect-m/ect2/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fect%2Dm%2Fect2%2FShared%20Documents%2FData%20Analysis&View=%7B8C7F09FA%2D5151%2D475C%2D93E7%2D470F22881AD2%7D

**Comment by shazadahmed10** [comment]
Tools were delivered to ECT2 on 1/22. Uploaded to the link above.
