### ISSUE TITLE
Malawi: Reverse TDY to ICPI

### ISSUE THREAD

**Issue by jb3436** [ICPI/Engagements#5]
Kondwani, a HETA fellow tacking on time in the US to sit at ICPI

**Comment by kkale25** [comment]
No interagency action needed. Kondwani and Biniyam will likely present a debrief of their activities as HETA fellows at the end of their visit (July). Happy to invite/share with ICPIers when that presentation occurs.

**Comment by kkale25** [comment]
Re-opening so we can include updates from Kondwani's work, including debrief.

**Comment by jb3436** [comment]
@kkale25 please uploade Kondwani's debrief PPT presentation to the sharepoint folder and include a link to it here and then please close this out again.
