### ISSUE TITLE
ST3 Request - TB/HIV (Infection Control)

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#50]
**Request**: Assess the infection control available data  from SIMS from 2015-2018 evaluating on a country basis how many facilities are tracked with how many have “green” dashboards.  We then would like to triangulate this data with the MERS data and other sources that identify TB cases at specific facilities. 

**Purpose**: This activity will identify areas and regions that would benefit from enhanced attention to infection prevention activities.  

**Requestor(s)**: Katy Godfrey (State/NIH) & Michelle Pearson (CDC)

**Status**:
Submitted 2/5
Discussed at leads 2/11
Approved 2/13/
Email Sent 2/25

**Analysts Assigned**:
Katya Noykhovich  - ICPI Liaison to S3
Meaghan Peterson – Analyst on project
Catherine Nichols – Technical reviewer

SharePoint Folder (pepfar.net)
--

ICPI>Engagements>[ST3 TB](https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FST3%20TB&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D&InitialTabId=Ribbon%2ERead&VisibilityContext=WSSTabPersistence)

**Comment by mehtasp** [comment]
Here's the 4.0 site level assessment tool (combines facility and community tools from 2.0-3.0). Each old CEE# corresponds with the new 4.0 CEE in the tool, which is really nice. I can see if I can find the old facility-level assessment tool in the meantime 
https://datim.zendesk.com/hc/en-us/articles/360020665471-SIMS-Site-Assessment-Tool

**Comment by mehtasp** [comment]
Ah [here ](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC-HQ%2Ficpi%2FProducts%2FICPI%20Data%20Store%2FSIMS%2FTraining%2FOptional%20Training%20Resources&FolderCTID=0x0120004DAC66286D0B8344836739DA850ACB95&View=%7B58E3102A-C027-4C66-A5C7-84FEBE208B3C%7D)are the facility and community assessment tools for 2.0-3.0!
