### ISSUE TITLE
 Cervical Cancer Request 

### ISSUE THREAD

**Issue by faithfawale** [ICPI/Engagements#56]
Request  Description

To identify if the Cervical Cancer Dossier and current dashboards are able to address the following analytical topics:

Data broken down by Global, by OU, a sheet for just the 8 CCP countries, by SNU, by facility, by funding agency, by implementing mechanism, by age bands (fine age plus 25-49).
Of the women living with HIV, how many/what % are on ART?
Of the women currently on ART, how many/what % did we screen for cervical cancer?
Of those, how many/what % screened positive for both of the SCRN_POS disaggregates? How many/what % were negative?
•	Positive disaggregate = precancerous lesion
•	Suspected cancer disaggregate = suspected cancer
Of the women screened for cervical cancer, for how many was it their: First screening, follow-up screening, rescreening, N/A?
Which treatment did they receive? VIA, LEEP, Thermocoagulation, N/A
Target/# screened/% of target reached/# of women to be screened to reach target

Since the dashboards and  the current dossier does not address all the above analytical topics, a tool will be created to address those specific analytical topics. The tool will be uploaded here  (https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FCervical%20Cancer&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D ). 

Timeline:
First Draft: 04/09/2019

**Comment by kkale25** [comment]
https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FShared%20Documents%2FICPI%20Engagement%2FCervical%20Cancer&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC002682B939F9BED347BD49E43D77D3C691&View=%7B94C838B2%2DE166%2D4122%2DB8B4%2D7BEB9E1BC12B%7D

**Comment by kkale25** [comment]
@faithfawale completed the dashboard and updated with FY19Q2 results here: https://www.pepfar.net/OGAC-HQ/icpi/Shared Documents/ICPI Engagement/Cervical Cancer/CCancer_Dashboard_05312019.xlsx

Kashmira emailed Jenny A. and Amber P. the updated dashboard. No additional next steps. Request complete.
