### ISSUE TITLE
CDI Public vs. NGO Sites Request

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#57]
Call scheduled with relevant CDI POCs on 4/4 at 8AM EST to discuss:
1.	Introductions (5 min)
2.	General discussion (20 min, All)
      -	What the analytic request is and what deliverable(s) the team expects
      -	What the timeline for this request is
      -	Who the POCs/leads from HQ and the country team are
      -	Which relevant iSMEs should be included in the process, if any
3.	Working session (25 min, country team, request POCs, etc.)
      -	Describe what the country team has already developed/is working on related to this request
      -	Share any data files or other analytics already developed/being developed
      -	Answer any early questions from ICPI related to the dataset, country context, etc. 
4.	Next steps (10 min)

Will update this ticket with new information as it comes in.

**Comment by kkale25** [comment]
Description of Request:
o	Identify whether there are certain distinctions between types of sites (NGOs vs pubic) and if there are performance differences in how those sites are doing across the cascade 
o	If there are sites doing better or worse (particularly high volume sites, looking at retention), then ICPI can help identify if there are certain characteristics that help explain those differences in performance (i.e., HRH)  

Timeline:
o	Data exploration/first thoughts from ICPI by Tuesday 4/9
o	First draft of analysis to team by Thursday 4/11
o	Country team to review and provide edits by Monday 4/15
o	Final draft to country team by Thursday 4/17 

POCs:
o	Country Team: Megan Swor, Etien Koua 
o	HQ: Lisa O’Brien, Kim Ahanda, Will Conquest, and Yoran G; OGAC Chair Heather Watts and PPM Caroline Cooney; Agency POCs to include relevant agency SI/M&E POCs as needed
o	ICPI: Travis Lim, Yaa Obeng-Aduasare, Kashmira Kale (Engagements Lead)

Next steps:
o	ACTION: Country team to send ICPI site-level full integrated dataset including program performance classifications and attributes

**Comment by wvp3** [comment]
Update from 4/4/2019: At the ICPI HSS/KP cluster working session, Travis and Gordon discussed the request.  The tentative plan moving forward is for two of us to split the work on the task, with Travis creating some visuals, and Gordon setting up some models, with input and review on both from the whole cluster.

- The visualizations will aim to display the HRH metrics and cadres that may be associated with both .  Examples of possible visuals include scatterplots at the site level, and box or violin plots comparing HRH support between types of sites.  

- The models will aim to compare the relationship between site characteristics (public/NGO, urban/rural, health center, PSNU, partner) and the program outcome.  Then we will attempt a mediator test by adding some HRH data to the model and see whether it obviates the statistically significant association between .  If it does, this provides some evidence that HRH a major mediator of the relationship between public/NGO and program performance.

**Comment by kkale25** [comment]
@wvp3 @aagordonaa 

PLease updated this ticket when you get a chance. Thanks!

**Comment by aagordonaa** [comment]
Update from 4/12/2019: Draft analysis circulated for comments:

•	This is of a multi-linear regression models that compare the relationship between site characteristics (public/NGO, urban/rural, health center) with linkage and retention.

•	Models were developed first in the absence of HRH, HRH data was later introduced to see whether the initial models changes the statistically significant association between characteristics.

**Comment by wvp3** [comment]
A final version was circulated to the entire HQ and country team to incorporate comments and feedback.
