### ISSUE TITLE
Finding Men COOP Request

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#58]
Summary: Request is being made to assist in the development of a tool to summarize country status in reaching,
engaging, and retaining men in HIV services

Objective: To better assist COOP in ranking/summarizing country status as it pertains to reaching, engaging, and
retaining men in HIV services.

Specific Deliverables: Global tool ranking/summarizing country status as it pertains to reaching, engaging, and retaining men in HIV services. The TSD tool may be a good starting point.

Requesting POCs: Carlos Toledo (CDC), Kristina Bishop (USAID)
ICPI POCs: Kashmira Kale (Engagements), Josh Davis/Aaron Chafetz (USAID), Jasmine Buttolph (Coordinator's Office)

**Comment by kkale25** [comment]
Call held to discuss request further on 4/17.
Attendees: Carlos Toledo, Kristina Bishop, Jasmine Buttloph, Kashmira Kale, Josh Davis

Notes:
-	Context for request
      o	Reaching Men COOP was first initiated to support issues around getting men tested;  now it’s evolved to include not only reaching men but also engaging them in treatment and retaining them in treatment for viral suppression 
      o	COOP hasn’t yet had discussions on MER indicators that are useful when evaluating how men are performing across the cascade; most of the COOP discussions thus far have been on how to implement rather than measuring/tracking 
-	Request: 
      o	Simple visualization(s) showing where each OU is in reaching, engaging, and retaining men (90-90-90 cascade); currently no tool where they can compare countries at the national level 
      o	Use current data (national and MER indicators) to better summarize this information for the COOP on a global level  will help with prioritization of TA
      o	This is just the primary analytic request  we can later begin to think of how PEPFAR is contributing to the gaps and drill down to further granular levels (either using current tools or developing newer visualizations)
-	Starting point/Next Steps:
      o	Look at Treatment Summary Dashboard (TSD) for OU-specific information 
      o	Josh Davis to “hack” Partner Progress Report (PPR) to show OU-level information (completed, find it here); Carlos and Kristina to review and let ICPI know if additional information is needed in the short term

**Comment by kkale25** [comment]
Kashmira shared the following analysis with Carlos and Kristina: https://www.pepfar.net/OGAC-HQ/icpi/Shared%20Documents/ICPI%20Engagement/Finding%20Men%20COOP/Finding%20Men%20COOP%20Request_DRAFT_05142019.xlsb

They would like to see this analysis include PLHIV data. Kashmira is working on gathering this data into a dataset and incorporating the updated request. 

Kashmira provided Carlos and Kristina with this update on 5/31/2019.

**Comment by jb3436** [comment]
Will wait for updated PLHIV data in order to refresh this analysis
