### ISSUE TITLE
HETA Fellow at ICPI: Ademola Oladipo

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#63]
Email sent to DC Community
--
Dear DC-Based ICPI Community, 

Please join us in welcoming a new team member to our DC-based ICPI community. Ademola is a HETA fellow with CDC and will be with ICPI through the end of July. The CDC team has worked with Ademola to identify the projects he will work on, and we look forward to collaborating with him as the projects progress.  

Below is Ademola’s bio, which you can also find in the Staff Directory on SharePoint. He is currently sitting in workspace 211 (through June) and will be in workspace 246 for June/July. Stop by and say hi! 

Ademola can be reached at: .....

## Bio
**Ademola Oladipo**
CDC HETA Fellow | Team Lead, Evaluation and Data Analytics (CDC, Nigeria)
Ademola joined the Data Use and Analytics Team (DUAT) of CDC as a new HETA fellow. He will work out of ICPI in Washington DC for the most part of the fellowship program. He will be exposed to new skills through project-based learning. Ademola shall focus on three main projects, working across teams and branches. Firstly, use case-based models to evaluate loss to follow up (LTFU) in pediatric and adolescent populations, focusing on the effect of aging out on LTFU data. Secondly, use modelling techniques to understand linkage to treatment in pediatric and adolescent populations, and perform cluster analysis. Thirdly, to evaluate the timing of mother to child transmission of HIV. The first and third projects will use patient-level data in electronic medical records. 
Ademola is from Nigeria, but has also lived in the United Kingdom for the later part of his education. He has a medical degree and, Masters and PhD in Public Health. He works with CDC Nigeria Epidemiology and Strategic Information Branch as Team Lead for the Monitoring, Evaluation and Data Analytics Team. He has over 16 years’ experience working in clinical medicine and public health at various levels of the health system. Four of those years are with CDC. He contributed to the development of the National Monitoring and Evaluation (M&E) Plans (National Operational Plan 2011-2014 and 2014-2018). He leads the development of data analytics and visualization for the National Data Repository (NDR) and the NigeriaMRS. In addition, he leads the CDC Nigeria’s effort to strengthen M&E systems, develop M&E plan and data management systems.
Of his 16 years’ experience, Ademola has committed 10 years to a career in Monitoring, Evaluation and Data Analysis. He provides technical expertise to improve HIV/TB, prevention and treatment, and development of sustainable data management systems for the Federal Ministry of Health (FMOH). He is a member of the National Strategic Information and Knowledge Management Technical Working Group. Early in his M&E career, he led the assessment of M&E systems in two states of Nigeria, which led to the development of the State M&E plans. Ademola is involved with design and implementation of evaluation and research projects for CDC Nigeria. Most recent is the Secondary Data Analysis Protocol from NDR. An umbrella protocol that would allow for evaluation studies for demonstrating program effectiveness and contribute to program planning and improvement. In addition, he leads analytics for data quality review and development of the Data Quality Assurance protocol. 
Ademola has a son, Tobi. Tobi is a huge blessing and a smart grade 8 lad. He has a lovely Rottweiler, fondly called Rex. He loves to listen to music, keep in touch with nature, family, and friends.

**Comment by jb3436** [comment]
BrownBag Debrief on NIgeria's Analytic Use Case and rTDY Project
--

July 8
Presentation on SP here

**Comment by jb3436** [comment]
Last day at ICPI July 19
Will process "offboarding" from being an on-site staff member to being a remote ICPI member. 
@hessionra

**Comment by hessionra** [comment]
Administrative Checklist
--

**To be completed by Coordination Office:**
- [ ] Update relevant Listservs
- [ ] Update relevant meeting invites

**Documents**
- [ ] Update ICPI Bio document
- [ ] Update ICPI Emergency Contact List

**Systems**
- [ ] Remove departing staff from GitHub
- [ ] Remove departing staff from Slack

**Comment by jb3436** [comment]
@hessionra please add a link to the brownbag presentation and close out the ticket.

**Comment by hessionra** [comment]
Ademola's presentation can be found on [SharePoint](https://www.pepfar.net/OGAC-HQ/icpi/Products/Forms/AllItems.aspx?RootFolder=%2FOGAC%2DHQ%2Ficpi%2FProducts%2FTraining%20and%20Webinars%2F2019%2FData%20Use%20for%20Action%20CDC%20Nigeria%20Brown%20Bag%2020190708&FolderCTID=0x012000C815322C717A7E4B8164EA374FA254EC00C3CC873FA325DD44884DEFC36053A859&View=%7B58E3102A%2DC027%2D4C66%2DA5C7%2D84FEBE208B3C%7D).
