### ISSUE TITLE
VMMC Coverage Request - Carlos Toledo

### ISSUE THREAD

**Issue by kkale25** [ICPI/Engagements#65]
VMMC Coverage Summary of Request
--

- PEPFAR has supported over 18.9 million voluntary medical male circumcisions (VMMC) since the program’s inception. 
- However, accurate, reliable estimates of the proportion of men circumcised nationally, or at sub-national levels which are crucial for program planning, are missing.  Various estimate sources exist that currently offer that information, however, discrepancies have been noted across all sources. 
- As countries continue to reach more and more men, accurate, reliable estimates of VMMC coverage will become increasingly important as plans are established to transition from the scale up phase of VMMC to a longer-term plan for maintaining high levels of MC coverage to sustain epidemic control. 
- The goal of this activity is to develop a tool that summarizes national and SNU-level coverage of medical circumcision (e.g., proportion of men medically circumcised) across 15 priority countries for VMMC, triangulated and validated through an agreed-on process that incorporates the full range of available data streams.  This will include circumcision coverage estimates in priority age bands (i.e., 15-29) and other age groups. 
- This tool will also aim to assist countries in longer-term planning for VMMC by establishing a way to plan for ongoing circumcision of rising cohorts of males as they age into the eligible population (at least 10 years of age). 

Objective of Request:
--

- Review currently available primary data sources (e.g., PEPFAR indicators, PHIA, MoH reporting, and others) and existing approaches/estimates (datapack, DMPPT2 tool, and others) to identify limitations and gaps in data. 
- Identify standardized data elements and a process for verification that  will produce reliable national and SNU-level coverage of medical circumcision. 
- Develop a tool that summarizes national and SNU-level coverage of medical circumcision (e.g., proportion of men medically circumcised) across 15 priority countries for VMMC and determine how this will relate to datapack values. 
- Propose changes to datapack process and PEPFAR MER Indicators to inform COP20 process and future reporting. 

 
Specific Deliverables
--

- Comparison table of data sources, variables collected, definitions used, process for verification 
- Tool summarizing national and SNU-level coverage of medical circumcision (e.g., proportion of men medically circumcised) across 15 priority countries for VMMC. 
- Agreed-on process and roles for incorporating available data streams to update tool at least annually 
- Recommendations to changes to datapack process and PEPFAR MER Indicators to inform COP20 and future reporting.

**Comment by kkale25** [comment]
Will be discussing at Leads on 6/3. Assigning Kimi and Erin as FYI for now.

**Comment by jb3436** [comment]
Discussed at leads 7/9 -  Suggestion to have the denominators team take the lead in determining next steps.

**Comment by jb3436** [comment]
Denominators Project may take this on. 
See description in Denominators Repo https://github.com/ICPI/Denominators/issues/1
