### ISSUE TITLE
DRC- Virtual Support

### ISSUE THREAD

**Issue by jb3436** [ICPI/Engagements#7]
Initial support - TDY for analytic support
Follow up TDY to transition tasks to country team
Current support - providing analytic support to team

**Comment by kkale25** [comment]
Hey @shazadahmed10 - any notable updates on this engagement? Otherwise will move to out of "Active"

Thanks!

**Comment by jb3436** [comment]
@shazadahmed10 Any updates on this? Should we close this out?
